In [1]:
#imports
import pandas as pd

In [4]:
#dataframe from excel
df = pd.read_excel(r'C:\Users\Michał\Documents\Python projects\public\jupyter_notebook\excel_files')
df

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Michał\\Documents\\Python projects\\public\\jupyter_notebook\\excel_files'

In [154]:
column_names = []
df['value_to_find'] = df['value_to_find'].replace('ND',-1) #because i want to have only numbers
for id_number in df.id:
    if df[df['id']==id_number].value_to_find.item()>0:
        data_row = df[df['id']==id_number]
        value_to_find = df[df['id']==id_number].value_to_find.item()
        column_names_temp = []
        for column in data_row:
            if data_row[column].item()==value_to_find and column!='value_to_find':
                column_names_temp.append(column)
        column_names.append(column_names_temp)
    else:
        data_row = df[df['id']==id_number]
        value_to_find = df[df['id']==id_number].value_to_find.item()
        column_names.append(str(value_to_find))
       
df['found_column'] = column_names
df

,id,column1,column2,column3,column4,column5,value_to_find,found_column
0,1,26186,16037,195.103,13302,195.103,195.103,"[column3, column5]"
1,2,5177,56129,2688,108.336,20656.000,108.336,[column4]
2,3,60311,77962,53414,3572,206.778,206.778,[column5]
3,4,42780,35263,ND,4659,1455.000,-1.000,-1.0
4,5,19570,493.587,31049,43063,43557.000,493.587,[column2]
5,6,99780,ND,87745,19192,18819.000,-1.000,-1.0
6,7,98409,ND,48230,17371,63874.000,-1.000,-1.0
7,8,17701,42343,87801,456.38,34052.000,456.380,[column4]
8,9,41636,7446,70578,171.3,59687.000,171.300,[column4]
9,10,99119,91589,3900,ND,92529.000,-1.000,-1.0
10,11,47107,98113,97572,364.458,36689.000,364.458,[column4]
11,12,83776,97946,ND,ND,49224.000,-1.000,-1.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             12 non-null     int64
 1   column1        12 non-null     int64
 2   column2        12 non-null     object
 3   column3        12 non-null     object
 4   column4        12 non-null     object
 5   column5        12 non-null     float64
 6   value_to_find  12 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 800.0+ bytes